//How many distinct terms are in the sequence generated by a^b for 2 = a = 100 and 2 = b = 100?


package problems;

import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class Problem_29 {

public static void main(String[] args) {
				
		Set<Double> mySet = Stream.iterate(2, e -> e + 1)
				                  .limit(99)
                                  .flatMap(e -> createAllExponentCases(e)
                                      .limit(99))
                                  .collect(Collectors.toCollection(TreeSet::new));
		
		System.out.println(mySet.size());
	}
	
	
	private static Double calculate(int base, int exponent) {
		return  Math.pow(base, exponent);
	}
		
	private static Stream<Double> createAllExponentCases(int base) {
		return Stream.iterate(2, e -> e + 1).map(e -> calculate(base, e));
	}
	
}